import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("published projection migration is registered", async () => {
  const migration = await readFile(new URL("../migrations/0016_published_projections.sql", import.meta.url), "utf8");
  assert.match(migration, /schema_migrations[\s\S]*0016_published_projections/i);
});

test("CFBD audit migrations are registered and health expects latest", async () => {
  const m17 = await readFile(new URL("../migrations/0017_cfbd_endpoint_audit.sql", import.meta.url), "utf8");
  const m18 = await readFile(new URL("../migrations/0018_cfbd_audit_tables_ensure.sql", import.meta.url), "utf8");
  const m19 = await readFile(new URL("../migrations/0019_cfb_player_projections.sql", import.meta.url), "utf8");
  const m20 = await readFile(new URL("../migrations/0020_action_apify_shadow.sql", import.meta.url), "utf8");
  const m21 = await readFile(new URL("../migrations/0021_action_apify_candidate.sql", import.meta.url), "utf8");
  const m22 = await readFile(new URL("../migrations/0022_action_apify_harden.sql", import.meta.url), "utf8");
  const m23 = await readFile(new URL("../migrations/0023_canonical_governance.sql", import.meta.url), "utf8");
  const m24 = await readFile(new URL("../migrations/0024_action_observation_timeseries.sql", import.meta.url), "utf8");
  const health = await readFile(new URL("../functions/api/health.js", import.meta.url), "utf8");
  const schemaExt = await readFile(new URL("../schema.extensions.sql", import.meta.url), "utf8");
  assert.match(m17, /schema_migrations[\s\S]*0017_cfbd_endpoint_audit/i);
  assert.match(m18, /schema_migrations[\s\S]*0018_cfbd_audit_tables_ensure/i);
  assert.match(m19, /schema_migrations[\s\S]*0019_cfb_player_projections/i);
  assert.match(m19, /cfb_player_role_snapshots/);
  assert.match(m19, /cfb_player_projections/);
  assert.match(m19, /cfb_prop_market_lines/);
  assert.match(m20, /schema_migrations[\s\S]*0020_action_apify_shadow/i);
  assert.match(m20, /shadow_provider_runs/);
  assert.match(m20, /shadow_market_observations/);
  assert.match(m20, /shadow_market_books/);
  assert.match(m20, /shadow_market_splits/);
  assert.match(m20, /shadow_line_movement/);
  assert.match(m20, /shadow_provider_comparisons/);
  assert.match(m21, /schema_migrations[\s\S]*0021_action_apify_candidate/i);
  assert.match(m21, /shadow_collection_runs/);
  assert.match(m21, /shadow_cost_ledger/);
  assert.match(m21, /shadow_provider_reliability/);
  assert.match(m21, /shadow_schema_fingerprints/);
  assert.match(m21, /shadow_promotion_metrics/);
  assert.match(m21, /shadow_dead_letters/);
  assert.match(m21, /shadow_observation_keys/);
  assert.match(schemaExt, /shadow_collection_runs/);
  assert.match(schemaExt, /shadow_cost_ledger/);
  assert.match(schemaExt, /shadow_observation_keys/);
  assert.match(m22, /schema_migrations[\s\S]*0022_action_apify_harden/i);
  assert.match(m22, /shadow_candidate_scheduler_state/);
  assert.match(schemaExt, /shadow_candidate_scheduler_state/);
  assert.match(m23, /schema_migrations[\s\S]*0023_canonical_governance/i);
  assert.match(m23, /canonical_source_registry/);
  assert.match(m23, /canonical_model_registry/);
  assert.match(m23, /canonical_misprice_snapshots/);
  assert.match(schemaExt, /canonical_source_registry/);
  assert.match(schemaExt, /canonical_model_registry/);
  assert.match(m24, /schema_migrations[\s\S]*0024_action_observation_timeseries/i);
  assert.match(m24, /action_market_book_observations/);
  assert.match(m24, /action_market_snapshot_pointers/);
  assert.match(m24, /money_minus_ticket_pct/);
  assert.match(m24, /public_ticket_pct/);
  assert.match(m24, /public_money_pct/);
  assert.match(schemaExt, /action_market_book_observations/);
  assert.match(schemaExt, /action_market_snapshot_pointers/);
  const m25 = await readFile(new URL("../migrations/0025_manual_completion_contracts.sql", import.meta.url), "utf8");
  assert.match(m25, /schema_migrations[\s\S]*0025_manual_completion_contracts/i);
  assert.match(m25, /canonical_publication_ledger/);
  assert.match(m25, /canonical_dq_findings/);
  assert.match(m25, /canonical_probability_provenance/);
  assert.match(m25, /canonical_promotion_evidence/);
  assert.match(schemaExt, /canonical_publication_ledger/);
  const m28 = await readFile(new URL("../migrations/0028_executed_bet_tracker_metadata.sql", import.meta.url), "utf8");
  assert.match(m28, /0028_executed_bet_tracker_metadata/i);
  assert.match(m28, /tracker_metadata_json/);
  const m29 = await readFile(new URL("../migrations/0029_executed_bet_settlement_evidence.sql", import.meta.url), "utf8");
  assert.match(m29, /0029_executed_bet_settlement_evidence/i);
  assert.match(m29, /final_home_score/);
  assert.match(health, /EXPECTED_MIGRATION_ID/);
  const m62 = await readFile(new URL("../migrations/0062_soccer_provider_mapping_registry.sql", import.meta.url), "utf8");
  assert.match(m62, /0062_soccer_provider_mapping_registry/i);
  assert.match(m62, /soccer_competition_provider_map/);
  assert.match(schemaExt, /soccer_competition_provider_map/);
  const m63 = await readFile(new URL("../migrations/0063_soccer_persistent_state_research.sql", import.meta.url), "utf8");
  assert.match(m63, /0063_soccer_persistent_state_research/i);
  assert.match(m63, /soccer_team_state/);
  assert.match(m63, /soccer_player_state/);
  assert.match(m63, /soccer_team_state_snapshots/);
  assert.match(schemaExt, /soccer_team_state/);
  const m64 = await readFile(new URL("../migrations/0064_soccer_phase3_validation_evidence.sql", import.meta.url), "utf8");
  assert.match(m64, /0064_soccer_phase3_validation_evidence/i);
  assert.match(m64, /soccer_validation_evidence/);
  const m67 = await readFile(new URL("../migrations/0067_soccer_phase3b_validation_provenance.sql", import.meta.url), "utf8");
  assert.match(m67, /0067_soccer_phase3b_validation_provenance/i);
  assert.match(m67, /snapshot_id/);
  assert.match(m67, /code_sha/);
  assert.match(schemaExt, /soccer_validation_evidence/);
  assert.match(schemaExt, /snapshot_id/);
  assert.match(schemaExt, /code_sha/);
  const m79 = await readFile(new URL("../migrations/0079_soccer_phase3f_research_routing.sql", import.meta.url), "utf8");
  assert.match(m79, /0079_soccer_phase3f_research_routing/i);
  assert.match(m79, /soccer_research_routes/);
  assert.match(m79, /soccer_prospective_shadow/);
  assert.match(m79, /phase3b-37456055406-1/);
  assert.match(m79, /9f65375491e99cac5497952eac5ad8326ae2e0a6/);
  assert.match(schemaExt, /soccer_research_routes/);
  assert.match(schemaExt, /soccer_prospective_shadow/);
  const m81Soccer = await readFile(new URL("../migrations/0081_soccer_phase3g_shadow_grading_fields.sql", import.meta.url), "utf8");
  assert.match(m81Soccer, /0081_soccer_phase3g_shadow_grading_fields/i);
  assert.match(m81Soccer, /v2_projection_value/);
  assert.match(m81Soccer, /v31_projection_value/);
  assert.match(m81Soccer, /v2_brier/);
  assert.match(m81Soccer, /v31_log_loss/);
  assert.match(schemaExt, /v2_projection_value/);
  assert.match(schemaExt, /v31_projection_value/);
  assert.match(schemaExt, /v2_brier/);
  assert.match(schemaExt, /v31_log_loss/);
  const m37 = await readFile(new URL("../migrations/0037_ops_control_plane.sql", import.meta.url), "utf8");
  assert.match(m37, /0037_ops_control_plane/i);
  assert.match(m37, /fbis_ops_components/);
  assert.match(m37, /fbis_ops_health/);
  assert.match(m37, /fbis_run_manifests/);
  assert.match(m37, /fbis_ops_invariant_checks/);
  assert.match(m37, /fbis_watchdog_metrics/);
  const m38 = await readFile(new URL("../migrations/0038_continuous_learning_governance.sql", import.meta.url), "utf8");
  assert.match(m38, /0038_continuous_learning_governance/i);
  assert.match(m38, /learning_monitor_runs/);
  assert.match(m38, /recalibration_runs/);
  assert.match(m38, /challenger_evaluations/);
  assert.match(m38, /bayesian_learning_state/);
  assert.match(m38, /online_learning_shadow/);
  assert.match(schemaExt, /learning_monitor_runs/);
  assert.match(schemaExt, /online_learning_shadow/);
  const m39 = await readFile(new URL("../migrations/0052_soccer_v2_features.sql", import.meta.url), "utf8");
  const m52 = await readFile(new URL("../migrations/0052_soccer_v2_features.sql", import.meta.url), "utf8");
  assert.match(m39, /0052_soccer_v2_features/i);
  assert.match(m39, /soccer_matches/);
  assert.match(m52, /0052_soccer_v2_features/);
  assert.match(m52, /home_xg/);
  assert.match(schemaExt, /soccer_matches/);
  assert.match(health, /actionApifyCandidateHealth/);
  assert.match(health, /WHERE id = \?/);
});

test("live CFBD audit artifact is checked in without secrets", async () => {
  const raw = await readFile(new URL("../data/cfbd/audits/live-23530f6.json", import.meta.url), "utf8");
  assert.equal(raw.includes("Bearer"), false);
  assert.equal(/CFBD_API_KEY[=:]\s*\S+/.test(raw), false);
  const audit = JSON.parse(raw);
  assert.equal(audit.job, "cfbd-endpoint-audit");
  assert.equal(audit.summary?.configured, true);
  assert.ok((audit.summary?.available || []).includes("/ppa/teams"));
  assert.ok((audit.summary?.available || []).includes("/games/weather"));
  assert.ok((audit.summary?.available || []).includes("/ratings/core"));
  assert.equal((audit.summary?.notEntitled || []).length, 0);
});


test("migration verifier audits numeric-prefix ambiguity", async () => {
  const verifier = await readFile(new URL("../scripts/verify-migrations.mjs", import.meta.url), "utf8");
  assert.match(verifier, /duplicatePrefixes/);
  assert.match(verifier, /legacyDuplicatePrefixes/);
  assert.match(verifier, /Unexpected duplicate numeric migration prefixes detected/);
});


test("migration lineage repair is forward-only and verifier blocks new ambiguity", async () => {
  const repair = await readFile(new URL("../migrations/0086_migration_lineage_reconciliation.sql", import.meta.url), "utf8");
  const verifier = await readFile(new URL("../scripts/verify-migrations.mjs", import.meta.url), "utf8");
  assert.match(repair, /0086_migration_lineage_reconciliation/);
  assert.match(repair, /0010_mlb_market_projections/);
  assert.doesNotMatch(repair, /\bDROP\b/i);
  assert.doesNotMatch(repair, /\bDELETE\b/i);
  assert.match(verifier, /legacyDuplicatePrefixes/);
  assert.match(verifier, /unexpectedDuplicatePrefixes/);
  assert.match(verifier, /legacyRegistrationExceptions/);
});


test("health migration tip is canonical and checked against repository latest", async () => {
  const tip = await readFile(new URL("../functions/lib/migrationTip.js", import.meta.url), "utf8");
  const health = await readFile(new URL("../functions/api/health.js", import.meta.url), "utf8");
  const verifier = await readFile(new URL("../scripts/verify-migrations.mjs", import.meta.url), "utf8");
  assert.match(tip, /0087_executed_bet_audit_backfill\.sql/);
  assert.match(tip, /0087_executed_bet_audit_backfill/);
  assert.match(health, /d1_migrations/);
  assert.match(health, /schema_migrations/);
  assert.match(health, /EXPECTED_MIGRATION_FILE/);
  assert.match(health, /EXPECTED_MIGRATION_ID/);
  assert.match(verifier, /files\.at\(-1\) !== EXPECTED_MIGRATION_FILE/);
});
