import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("published projection migration is registered", async () => {
  const migration = await readFile(new URL("../migrations/0016_published_projections.sql", import.meta.url), "utf8");
  assert.match(migration, /schema_migrations[\s\S]*0016_published_projections/i);
});

test("CFBD audit migrations are registered and health expects latest", async () => {
  const m17 = await readFile(new URL("../migrations/0017_cfbd_endpoint_audit.sql", import.meta.url), "utf8");
  const m18 = await readFile(new URL("../migrations/0018_cfbd_audit_tables_ensure.sql", import.meta.url), "utf8");
  const m19 = await readFile(new URL("../migrations/0019_cfb_player_projections.sql", import.meta.url), "utf8");
  const m20 = await readFile(new URL("../migrations/0020_action_apify_shadow.sql", import.meta.url), "utf8");
  const m21 = await readFile(new URL("../migrations/0021_action_apify_candidate.sql", import.meta.url), "utf8");
  const m22 = await readFile(new URL("../migrations/0022_action_apify_harden.sql", import.meta.url), "utf8");
  const m23 = await readFile(new URL("../migrations/0023_canonical_governance.sql", import.meta.url), "utf8");
  const m24 = await readFile(new URL("../migrations/0024_action_observation_timeseries.sql", import.meta.url), "utf8");
  const health = await readFile(new URL("../functions/api/health.js", import.meta.url), "utf8");
  const schemaExt = await readFile(new URL("../schema.extensions.sql", import.meta.url), "utf8");
  assert.match(m17, /schema_migrations[\s\S]*0017_cfbd_endpoint_audit/i);
  assert.match(m18, /schema_migrations[\s\S]*0018_cfbd_audit_tables_ensure/i);
  assert.match(m19, /schema_migrations[\s\S]*0019_cfb_player_projections/i);
  assert.match(m19, /cfb_player_role_snapshots/);
  assert.match(m19, /cfb_player_projections/);
  assert.match(m19, /cfb_prop_market_lines/);
  assert.match(m20, /schema_migrations[\s\S]*0020_action_apify_shadow/i);
  assert.match(m20, /shadow_provider_runs/);
  assert.match(m20, /shadow_market_observations/);
  assert.match(m20, /shadow_market_books/);
  assert.match(m20, /shadow_market_splits/);
  assert.match(m20, /shadow_line_movement/);
  assert.match(m20, /shadow_provider_comparisons/);
  assert.match(m21, /schema_migrations[\s\S]*0021_action_apify_candidate/i);
  assert.match(m21, /shadow_collection_runs/);
  assert.match(m21, /shadow_cost_ledger/);
  assert.match(m21, /shadow_provider_reliability/);
  assert.match(m21, /shadow_schema_fingerprints/);
  assert.match(m21, /shadow_promotion_metrics/);
  assert.match(m21, /shadow_dead_letters/);
  assert.match(m21, /shadow_observation_keys/);
  assert.match(schemaExt, /shadow_collection_runs/);
  assert.match(schemaExt, /shadow_cost_ledger/);
  assert.match(schemaExt, /shadow_observation_keys/);
  assert.match(m22, /schema_migrations[\s\S]*0022_action_apify_harden/i);
  assert.match(m22, /shadow_candidate_scheduler_state/);
  assert.match(schemaExt, /shadow_candidate_scheduler_state/);
  assert.match(m23, /schema_migrations[\s\S]*0023_canonical_governance/i);
  assert.match(m23, /canonical_source_registry/);
  assert.match(m23, /canonical_model_registry/);
  assert.match(m23, /canonical_misprice_snapshots/);
  assert.match(schemaExt, /canonical_source_registry/);
  assert.match(schemaExt, /canonical_model_registry/);
  assert.match(m24, /schema_migrations[\s\S]*0024_action_observation_timeseries/i);
  assert.match(m24, /action_market_book_observations/);
  assert.match(m24, /action_market_snapshot_pointers/);
  assert.match(m24, /money_minus_ticket_pct/);
  assert.match(m24, /public_ticket_pct/);
  assert.match(m24, /public_money_pct/);
  assert.match(schemaExt, /action_market_book_observations/);
  assert.match(schemaExt, /action_market_snapshot_pointers/);
  assert.match(health, /EXPECTED_MIGRATION\s*=\s*["']0024_action_observation_timeseries["']/);
  assert.match(health, /actionApifyCandidateHealth/);
  assert.match(health, /WHERE id = \?/);
});

test("live CFBD audit artifact is checked in without secrets", async () => {
  const raw = await readFile(new URL("../data/cfbd/audits/live-23530f6.json", import.meta.url), "utf8");
  assert.equal(raw.includes("Bearer"), false);
  assert.equal(/CFBD_API_KEY[=:]\s*\S+/.test(raw), false);
  const audit = JSON.parse(raw);
  assert.equal(audit.job, "cfbd-endpoint-audit");
  assert.equal(audit.summary?.configured, true);
  assert.ok((audit.summary?.available || []).includes("/ppa/teams"));
  assert.ok((audit.summary?.available || []).includes("/games/weather"));
  assert.ok((audit.summary?.available || []).includes("/ratings/core"));
  assert.equal((audit.summary?.notEntitled || []).length, 0);
});
