/**
 * CBB program requirement audit — separates baseline from full manual.
 *
 * possessions×PPP baseline = IMPLEMENTED_RESEARCH_ONLY
 * Broader CBB manual components classified individually.
 */

export const CBB_PROGRAM_REQUIREMENTS = Object.freeze([
  {
    requirement: "possessions_x_ppp_baseline_challenger",
    status: "IMPLEMENTED_RESEARCH_ONLY",
    adapter: null,
    persistence: null,
    module: "functions/lib/cbbPureChallenger.js",
    test: "test/manual-completion-integrity.test.js / test/functional-pipeline.test.js",
    maturity: "research",
    blocker: null,
  },
  {
    requirement: "cbbd_adapter_and_raw_archival",
    status: "IMPLEMENTED",
    adapter: "functions/lib/collegeApi.js (cbbdGet) / cfbd.js loadCbbdRatings",
    persistence: "college store + R2 archive paths via collegeJobs",
    module: "functions/lib/cbbRatings.js, collegeApply.js",
    test: "test/college.test.js",
    maturity: "production_research_shared",
    blocker: null,
  },
  {
    requirement: "kenpom_api_adapter",
    status: "IMPLEMENTATION_PENDING",
    adapter: null,
    persistence: null,
    module: "functions/lib/cbbRatings.js kenpomAbsent() stub",
    test: null,
    maturity: "none",
    blocker: "No KenPom API client; registry declaration only",
  },
  {
    requirement: "torvik_bulk_file_adapter",
    status: "IMPLEMENTATION_PENDING",
    adapter: null,
    persistence: null,
    module: "functions/lib/cbbRatings.js torvikUnavailable() stub",
    test: null,
    maturity: "none",
    blocker: "No Torvik bulk ingest",
  },
  {
    requirement: "pit_ratings_snapshots",
    status: "IMPLEMENTED_SCAFFOLD",
    adapter: "lineageContract.assertPointInTime",
    persistence: "challenger freeze cutoff via collegeJobsCore.featureCutoffIso",
    module: "functions/lib/canonical/lineageContract.js",
    test: "test/manual-completion-integrity.test.js",
    maturity: "shared_helper",
    blocker: "No dedicated CBB source-specific PIT ratings snapshot store",
  },
  {
    requirement: "source_specific_lineage_kenpom_vs_torvik_vs_cbbd",
    status: "IMPLEMENTED_SCAFFOLD",
    adapter: "sourceRegistry declarations",
    persistence: null,
    module: "functions/lib/canonical/sourceRegistry.js",
    test: "test/canonical-governance.test.js",
    maturity: "registry_only",
    blocker: "KenPom/Torvik adapters missing — lineage cannot bind live payloads",
  },
  {
    requirement: "possession_efficiency_feature_registry",
    status: "IMPLEMENTED_SCAFFOLD",
    adapter: null,
    persistence: null,
    module: "functions/lib/canonical/featureRegistry.js (cbb.pure.* declarations)",
    test: null,
    maturity: "declaration",
    blocker: "Registry entries label kenpom_api without live adapter",
  },
  {
    requirement: "richer_matchup_features_beyond_oe_de_tempo",
    status: "IMPLEMENTATION_PENDING",
    adapter: null,
    persistence: null,
    module: null,
    test: null,
    maturity: "none",
    blocker: "Manual matchup stack not built",
  },
  {
    requirement: "expected_minutes_player_opportunity_architecture",
    status: "IMPLEMENTATION_PENDING",
    adapter: null,
    persistence: null,
    module: null,
    test: null,
    maturity: "none",
    blocker: "CBB player opportunity not implemented (NBA helper only)",
  },
  {
    requirement: "player_stat_models",
    status: "IMPLEMENTATION_PENDING",
    adapter: null,
    persistence: null,
    module: null,
    test: null,
    maturity: "none",
    blocker: null,
  },
  {
    requirement: "training_artifacts",
    status: "IMPLEMENTED_SCAFFOLD",
    adapter: null,
    persistence: "data/models/cbb-reg-v1.js schema",
    module: "data/models/cbb-reg-v1.js",
    test: null,
    maturity: "artifact_schema",
    blocker: "PURE challenger has no fitted artifact distinct from CBBD ratings shadow",
  },
  {
    requirement: "rolling_expanding_walk_forward_runner",
    status: "IMPLEMENTED",
    adapter: null,
    persistence: "validation runs via college store",
    module: "functions/lib/collegeJobs.js temporalValidationFolds / model-train-validate",
    test: "test/research-validation.test.js / model-lab",
    maturity: "shared_college_jobs",
    blocker: "CBB-FBIS-PURE specific OOS series not yet accumulated",
  },
  {
    requirement: "frozen_challenger_predictions",
    status: "IMPLEMENTED",
    adapter: null,
    persistence: "model_predictions D1",
    module: "functions/lib/collegeJobsCore.js freezeChallengerPredictions",
    test: "test/college.test.js / research paths",
    maturity: "shared",
    blocker: null,
  },
  {
    requirement: "grading",
    status: "IMPLEMENTED",
    adapter: null,
    persistence: "gradeModelPrediction",
    module: "functions/lib/collegeJobsCore.js gradeScores",
    test: "test/model-lab.test.js",
    maturity: "shared",
    blocker: null,
  },
  {
    requirement: "baseline_comparison",
    status: "IMPLEMENTED",
    adapter: null,
    persistence: null,
    module: "functions/lib/modelLab.js",
    test: "test/model-lab.test.js",
    maturity: "shared",
    blocker: null,
  },
  {
    requirement: "pinnacle_paired_error_comparison",
    status: "IMPLEMENTED",
    adapter: null,
    persistence: null,
    module: "functions/lib/modelLab.js pairedModelComparison; collegeJobs promote ref CBB-PINNACLE-IMPLIED",
    test: "test/model-lab.test.js",
    maturity: "shared",
    blocker: "Applies to frozen college challengers; PURE v0 series still thin",
  },
]);

export function cbbProgramAudit() {
  const counts = {
    IMPLEMENTED: 0,
    IMPLEMENTED_RESEARCH_ONLY: 0,
    IMPLEMENTED_SCAFFOLD: 0,
    IMPLEMENTATION_PENDING: 0,
    VALIDATION_PENDING: 0,
    OOS_DATA_PENDING: 0,
    PROVIDER_OR_LICENSE_BLOCKED: 0,
    OPERATOR_PROMOTION_REQUIRED: 0,
  };
  for (const r of CBB_PROGRAM_REQUIREMENTS) {
    counts[r.status] = (counts[r.status] || 0) + 1;
  }
  return {
    baseline: "possessions×PPP = IMPLEMENTED_RESEARCH_ONLY — not full manual complete",
    requirements: CBB_PROGRAM_REQUIREMENTS,
    counts,
    oosDataPendingEligible: false,
    note: "Do not label complete CBB manual OOS_DATA_PENDING; too much IMPLEMENTATION_PENDING remains",
  };
}
