/**
 * Heritage soccer wagering universe.
 * Provider IDs are resolved dynamically by name/aliases; they are not hard-coded here.
 * Futures are tracked separately from match projection markets.
 */
export const HERITAGE_SOCCER_COMPETITIONS = Object.freeze([
  { key:"arg.copa", name:"Argentina Copa Argentina", country:"ARG", type:"cup", calendar:"calendar", aliases:["Copa Argentina"] },
  { key:"arg.1", name:"Argentina Liga Profesional", country:"ARG", type:"league", calendar:"calendar", aliases:["Liga Profesional","Liga Profesional de Fútbol","Argentine Primera División"] },
  { key:"bel.1", name:"Belgium Jupiler League", country:"BEL", type:"league", calendar:"fall-spring", aliases:["Jupiler Pro League","Belgian Pro League"] },
  { key:"bra.1", name:"Brazil Serie A", country:"BRA", type:"league", calendar:"calendar", aliases:["Brasileirão Série A","Serie A Brazil"] },
  { key:"conmebol.sudamericana", name:"CONMEBOL Copa Sudamericana", country:"INTL", type:"continental-cup", calendar:"calendar", aliases:["Copa Sudamericana"] },
  { key:"conmebol.libertadores", name:"Copa Libertadores", country:"INTL", type:"continental-cup", calendar:"calendar", aliases:["CONMEBOL Libertadores","Copa Libertadores"] },
  { key:"den.1", name:"Denmark Superligaen", country:"DEN", type:"league", calendar:"fall-spring", aliases:["Danish Superliga","Superliga"] },
  { key:"eng.2", name:"England Championship", country:"ENG", type:"league", calendar:"fall-spring", aliases:["Championship","EFL Championship"] },
  { key:"eng.league_cup", name:"England EFL Cup", country:"ENG", type:"cup", calendar:"fall-spring", aliases:["EFL Cup","League Cup","Carabao Cup"] },
  { key:"eng.fa_cup", name:"England FA Cup", country:"ENG", type:"cup", calendar:"fall-spring", aliases:["FA Cup"] },
  { key:"eng.1", name:"England Premier League", country:"ENG", type:"league", calendar:"fall-spring", aliases:["Premier League"] },
  { key:"fra.1", name:"France Ligue 1", country:"FRA", type:"league", calendar:"fall-spring", aliases:["Ligue 1"] },
  { key:"ger.1", name:"Germany Bundesliga", country:"GER", type:"league", calendar:"fall-spring", aliases:["Bundesliga"] },
  { key:"ger.pokal", name:"Germany DFB Pokal", country:"GER", type:"cup", calendar:"fall-spring", aliases:["DFB Pokal","DFB-Pokal"] },
  { key:"intl.club_friendly", name:"International Club Friendlies Soccer", country:"INTL", type:"friendly", calendar:"mixed", aliases:["Club Friendly","Club Friendlies"] },
  { key:"intl.friendly", name:"International Friendlies National Teams", country:"INTL", type:"international-friendly", calendar:"mixed", aliases:["International Friendly","Friendlies"] },
  { key:"uefa.conference", name:"International UEFA Conference League", country:"INTL", type:"continental-cup", calendar:"fall-spring", aliases:["UEFA Conference League","Conference League"] },
  { key:"uefa.nations", name:"International UEFA Nations League", country:"INTL", type:"international-cup", calendar:"cycle", aliases:["UEFA Nations League","Nations League"] },
  { key:"ita.1", name:"Italy Serie A", country:"ITA", type:"league", calendar:"fall-spring", aliases:["Serie A"] },
  { key:"usa.1", name:"Major League Soccer", country:"USA", type:"league", calendar:"calendar", aliases:["MLS","Major League Soccer"] },
  { key:"mex.1", name:"Mexico Liga MX", country:"MEX", type:"league", calendar:"split", aliases:["Liga MX"] },
  { key:"ned.1", name:"Netherlands Eredivisie", country:"NED", type:"league", calendar:"fall-spring", aliases:["Eredivisie"] },
  { key:"por.1", name:"Portugal Primeira Liga", country:"POR", type:"league", calendar:"fall-spring", aliases:["Primeira Liga","Liga Portugal"] },
  { key:"sco.1", name:"Scotland Premiership", country:"SCO", type:"league", calendar:"fall-spring", aliases:["Scottish Premiership","Premiership"] },
  { key:"esp.1", name:"Spain La Liga", country:"ESP", type:"league", calendar:"fall-spring", aliases:["LaLiga","La Liga"] },
  { key:"tur.1", name:"Turkey Super Lig", country:"TUR", type:"league", calendar:"fall-spring", aliases:["Süper Lig","Super Lig"] },
  { key:"uefa.champions", name:"UEFA Champions League", country:"INTL", type:"continental-cup", calendar:"fall-spring", aliases:["Champions League","UEFA Champions League"] },
  { key:"uefa.europa", name:"UEFA Europa League", country:"INTL", type:"continental-cup", calendar:"fall-spring", aliases:["Europa League","UEFA Europa League"] },
  { key:"usa.usl_championship", name:"United States USL Championship", country:"USA", type:"league", calendar:"calendar", aliases:["USL Championship"] },
]);

export const HERITAGE_SOCCER_FUTURES = Object.freeze([
 "Belgium Jupiler League Futures","Brazil Serie A Futures","Denmark Superligaen Futures","England Championship Futures",
 "England FA Cup Futures","England Premier League Futures","Euro 2028 Futures","France Ligue 1 Futures","Germany Bundesliga Futures",
 "Germany DFB Pokal Futures","International Copa Libertadores Futures","International Copa Sudamericana Futures",
 "International FIFA World Cup Futures","International UEFA Europa League Futures","International UEFA Nations League Futures",
 "Italy Serie A Futures","Mexico Liga MX 2026 Futures","Scotland Premiership Futures","Spain La Liga Futures",
 "UEFA Champions League Futures","UEFA Conference League Futures","United States MLS Futures"
]);

export const SOCCER_COMPETITION_POLICY = Object.freeze({
  league: { matchModel:true, crossCompetitionPrior:false, uncertaintyFloor:"LOW" },
  cup: { matchModel:true, crossCompetitionPrior:true, uncertaintyFloor:"MEDIUM" },
  "continental-cup": { matchModel:true, crossCompetitionPrior:true, uncertaintyFloor:"MEDIUM" },
  "international-cup": { matchModel:true, crossCompetitionPrior:true, uncertaintyFloor:"MEDIUM" },
  friendly: { matchModel:true, crossCompetitionPrior:true, uncertaintyFloor:"HIGH", starCap:2 },
  "international-friendly": { matchModel:true, crossCompetitionPrior:true, uncertaintyFloor:"HIGH", starCap:2 },
});

export function heritageSoccerCompetition(keyOrName){
  const q=String(keyOrName||"").toLowerCase().trim();
  return HERITAGE_SOCCER_COMPETITIONS.find(c=>c.key.toLowerCase()===q||c.name.toLowerCase()===q||c.aliases.some(a=>a.toLowerCase()===q))||null;
}

export function isHeritageSoccerMatchCompetition(v){return Boolean(heritageSoccerCompetition(v));}

export const HERITAGE_SOCCER_EXTENDED_OFFERINGS = Object.freeze([
  "Albania Cup",
  "Argentina Primera B Metropolitana",
  "Argentina Primera B Metropolitana Reserves",
  "Argentina Primera C Metropolitana",
  "Argentina Primera C Metropolitana Reserves",
  "Argentina Primera Nacional",
  "Australia A League",
  "Australia Cup",
  "Austria 2 Liga",
  "Austria Bundesliga",
  "Bangladesh Federation Cup",
  "Belgium Challenger Pro League",
  "Bolivia Copa Pacena",
  "Bolivia Liga Profesional",
  "Bosnia-Herz Premijer Liga BiH",
  "Brazil Brasileiro Serie B",
  "Brazil Campeonato Mineiro Segunda Divisao",
  "Brazil Carioca B2",
  "Brazil Copa do Brazil",
  "Brazil Copa Goias Division 2 U20",
  "Brazil Paraibano 2",
  "Bulgaria Parva Liga",
  "Bulgaria Vtora liga",
  "Cambodia Cup",
  "Canada Premier League",
  "Chile Copa Chile",
  "Chile Primera Division",
  "China League One",
  "China League Two",
  "China Super League",
  "Colombia Primera A",
  "Colombia Primera B",
  "Copa Ecuador",
  "Costa Rica Primera Division",
  "Croatia 1 HNL",
  "Croatia 1. NL",
  "Cyprus Division 1",
  "Czech Republic Chance Národní Liga",
  "Czech Republic First League",
  "Denmark 1st division",
  "Ecuador Liga Pro Serie A",
  "Egypt Premier League",
  "England EFL Trophy",
  "England Isthmian League North",
  "England Isthmian League Premier",
  "England Isthmian League South Center",
  "England League One",
  "England League Two",
  "England National League",
  "England National League Cup",
  "England National League South",
  "England Northern Premier League",
  "England Northern Premier League Division One",
  "England Professional Development U21 League",
  "England Southern Football League Division One",
  "England Southern Premier League Division South",
  "Estonia Premium Liiga",
  "Fiji Inter District Championship",
  "Finland Veikkausliiga",
  "Finland Ykkonen",
  "Finland Ykkosliiga",
  "France Ligue 2",
  "France Ligue 3",
  "Friendlies International U19",
  "Germany 2. Bundesliga",
  "Germany 3 Liga",
  "Greece Super League",
  "Greece. Cup",
  "Honduras Liga Nacional",
  "Hungary Liga NB II",
  "Hungary OTP Bank Liga",
  "Iceland Urvalsdeild",
  "India Bangalore - Super Division",
  "India Calcutta Division 1",
  "India Shillong Division 1",
  "Indonesia Super League",
  "International Africa Cup of Nations",
  "International Africa Cup of Nations - U23",
  "International Africa. Cup of Nations U20",
  "International CONCACAF Nations League",
  "International Friendlies National Teams - U20",
  "International Friendly U23",
  "International Gulf Cup of Nations",
  "International National Friendlies - U19 Women",
  "International UEFA European Championship U19 Women",
  "Ireland 1st Division",
  "Ireland National League",
  "Ireland Premier Division",
  "Israel Premier League",
  "Italy Serie B",
  "Jamaica Premier League",
  "Japan J1 League",
  "Japan J2 League",
  "Kenya Premier League",
  "Mexico Liga de Expansion MX",
  "Mexico Liga Primera Premier",
  "Mexico Promesas Cup",
  "Netherlands Eerste Divisie",
  "Nicaragua Liga de Ascenso",
  "Nicaragua Primera Division",
  "Northern Ireland Premier League",
  "Norway 3 Division",
  "Norway Eliteserien",
  "Norway NM Cupen",
  "Norway Obos Ligaen",
  "Paraguay Division Intermedia",
  "Paraguay EFE Cup W",
  "Paraguay Primera Division",
  "Peru Primera Division",
  "Peru Segunda Division",
  "Poland 1 Liga",
  "Poland Ekstraklasa",
  "Portugal Liga Next Gen U23",
  "Portugal Segunda Liga",
  "Qatar Stars League",
  "Romania Liga 2",
  "Romania Superliga",
  "Russian Premier League",
  "Saudi Arabia Professional League",
  "Scotland Championship",
  "Scotland League One",
  "Scotland League Two",
  "Serbia Super Liga",
  "Slovakia Super Liga",
  "Slovenia 2 Liga",
  "Slovenia Prva Liga",
  "South Korea K League Classic",
  "South Korea K2 League",
  "Spain La Liga 2",
  "Sweden Allsvenskan",
  "Sweden Superettan",
  "Sweden Svenska Cupen",
  "Switzerland Challenge League",
  "Switzerland Super League",
  "Turkey 1. Lig",
  "Turkey 2. Lig",
  "UEFA European Championship - U21",
  "Ukraine Cup",
  "Ukraine Premier League",
  "Uruguay Primera Division",
  "Uruguay Primera Divisional C",
  "Venezuela Primera Division",
  "Vietnam National Cup",
  "Wales Cymru Championship South",
  "Wales Premier League"
]);

const DEVELOPMENT_RE = /(?:reserves?|\bu-?\d{2}\b|\bu\d{2}\b|promesas|next gen|professional development|women)/i;
const FRIENDLY_RE = /friendl/i;
const LOW_TIER_RE = /(?:ist(h)?mian|northern premier|southern football|southern premier|division one|3 division|primera divisional c|carioca b2|paraibano 2|campeonato mineiro segunda|bangalore|calcutta|shillong|ykkonen\b|copa goias division 2)/i;

export function heritageSoccerOfferingTier(name){
  const s=String(name||"");
  if(DEVELOPMENT_RE.test(s)) return {tier:"D",modelEligible:false,reason:"YOUTH_RESERVE_OR_DEVELOPMENT"};
  if(FRIENDLY_RE.test(s)) return {tier:"D",modelEligible:false,reason:"FRIENDLY_HIGH_ROSTER_UNCERTAINTY"};
  if(LOW_TIER_RE.test(s)) return {tier:"C",modelEligible:false,reason:"LOW_DATA_OR_THIN_COMPETITION"};
  return {tier:"DISCOVERY",modelEligible:null,reason:"REQUIRES_PITCHAPI_COVERAGE_AND_HISTORY_AUDIT"};
}

export function heritageSoccerAllOfferings(){
  return [...HERITAGE_SOCCER_COMPETITIONS.map(x=>x.name),...HERITAGE_SOCCER_EXTENDED_OFFERINGS,...HERITAGE_SOCCER_FUTURES];
}
